import { useI18n } from "@/lib/i18n";
/** Traduz rótulos de apresentação sem alterar os valores usados nas APIs e nos filtros. */
const labels: Record<string,string> = {
  "Champions": "Campeões",
  "Loyal": "Fiéis",
  "Potential": "Potenciais",
  "Promising": "Promissores",
  "At Risk": "Em risco",
  "AtRisk": "Em risco",
  "Lost": "Perdidos",
  "High Conversion": "Alta conversão",
  "Standard": "Padrão",
  "Low": "Baixa conversão",
  "PENDING": "Pendente",
  "APPROVED": "Aprovado",
  "REJECTED": "Recusado",
  "CANCELLED": "Cancelado",
  "SHIPPED": "Enviado",
  "DELIVERED": "Entregue",
  "ACTIVE": "Ativo",
  "INACTIVE": "Inativo",
  "DISCONTINUED": "Descontinuado",
  "VISIT": "Visita",
  "REGISTRATION": "Cadastro",
  "APPROVED_REGISTRATION": "Cadastro aprovado",
  "PRODUCT_VIEW": "Visualização de produto",
  "ADD_TO_CART": "Adição ao carrinho",
  "CHECKOUT_STARTED": "Checkout iniciado",
  "PURCHASE": "Compra",
  "ADMIN": "Administrador",
  "CLIENT": "Cliente",
  "NEW": "Novo",
  "RETURNING": "Recorrente",
  "Referral": "Indicação",
  "Organic": "Orgânico",
  "Direct": "Direto",
  "pending": "Pendente",
  "approved": "Aprovado",
  "rejected": "Recusado",
  "active": "Ativo",
  "checking": "Verificando",
  "Registration": "Cadastro",
  "Approved Registration": "Cadastro aprovado",
  "Add to Cart": "Adição ao carrinho",
  "Product View": "Visualização de produto",
  "Checkout": "Checkout",
  "Purchase": "Compra",
  "Site Visits": "Visitas ao site",
  "Orders": "Pedidos",
  "Revenue": "Faturamento",
  "revenue": "Faturamento",
  "spend": "Investimento",
  "leads": "Leads",
  "buyers": "Compradores",
  "nonBuyers": "Não compradores",
  "units": "Unidades",
  "price": "Preço",
  "stock": "Estoque"
};
export function displayLabel(value: string | null | undefined): string { return value == null ? "—" : labels[value] ?? value; }
/** Igual a displayLabel em portugues; em en/ko mantem o valor original (a main nunca traduziu esses rotulos para o portugues). */
export function useDisplayLabel(): (value: string | null | undefined) => string {
  const { language } = useI18n();
  return (value) => (language === "pt" ? displayLabel(value) : value == null ? "—" : value);
}
