import {
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { nanoid } from "nanoid";
import { clientsTable } from "./clients";
import { customersTable } from "./customers";
import { whatsappContactsTable, whatsappConversationsTable, whatsappMessagesTable } from "./whatsapp";

export const upzeroIntegrationsTable = pgTable("upzero_integrations", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  baseUrl: text("base_url").notNull().default("https://api.upzero.com.br"),
  authType: text("auth_type", { enum: ["api_key", "bearer"] }).notNull().default("api_key"),
  encryptedApiKey: text("encrypted_api_key"),
  encryptedToken: text("encrypted_token"),
  storeExternalId: text("store_external_id"),
  tenantId: text("tenant_id"),
  environment: text("environment").notNull().default("production"),
  status: text("status").notNull().default("not_configured"),
  lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
  lastError: text("last_error"),
  rawConfig: jsonb("raw_config"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("upzero_integrations_client_idx").on(table.clientId),
  clientUnique: uniqueIndex("upzero_integrations_client_unique").on(table.clientId),
}));

export const aiCommercialOperationsTable = pgTable("ai_commercial_operations", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("paused"),
  autonomyMode: text("autonomy_mode").notNull().default("assisted"),
  orderFlowMode: text("order_flow_mode").notNull().default("pre_order_stock_confirmation"),
  priceRequiresApprovedRegistration: boolean("price_requires_approved_registration").notNull().default(true),
  allowCatalogWithoutPrice: boolean("allow_catalog_without_price").notNull().default(true),
  allowProductWithoutPrice: boolean("allow_product_without_price").notNull().default(true),
  allowAutoRegistration: boolean("allow_auto_registration").notNull().default(false),
  requireHumanApprovalBeforeRegistrationPost: boolean("require_human_approval_before_registration_post").notNull().default(true),
  allowPreOrderCreation: boolean("allow_pre_order_creation").notNull().default(false),
  allowCheckoutLink: boolean("allow_checkout_link").notNull().default(false),
  stockConfirmationRequired: boolean("stock_confirmation_required").notNull().default(true),
  shippingAfterStockConfirmation: boolean("shipping_after_stock_confirmation").notNull().default(true),
  paymentAfterStockConfirmation: boolean("payment_after_stock_confirmation").notNull().default(true),
  handoffHighValueThreshold: doublePrecision("handoff_high_value_threshold").notNull().default(0),
  dailyCostLimit: doublePrecision("daily_cost_limit").notNull().default(0),
  monthlyCostLimit: doublePrecision("monthly_cost_limit").notNull().default(0),
  pauseOnCostLimit: boolean("pause_on_cost_limit").notNull().default(true),
  alertCostPercent: doublePrecision("alert_cost_percent").notNull().default(80),
  currency: text("currency").notNull().default("BRL"),
  usdBrlRate: doublePrecision("usd_brl_rate").notNull().default(5),
  agencyMarkupPercent: doublePrecision("agency_markup_percent").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_commercial_operations_client_idx").on(table.clientId),
  statusIdx: index("ai_commercial_operations_status_idx").on(table.clientId, table.status),
}));

export const aiAgentConfigsTable = pgTable("ai_agent_configs", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  operationId: text("operation_id").references(() => aiCommercialOperationsTable.id, { onDelete: "cascade" }),
  agentType: text("agent_type").notNull(),
  name: text("name").notNull(),
  status: text("status").notNull().default("active"),
  model: text("model").notNull().default("gpt-4.1-mini"),
  temperature: doublePrecision("temperature").notNull().default(0.2),
  maxInputTokens: integer("max_input_tokens").notNull().default(12000),
  maxOutputTokens: integer("max_output_tokens").notNull().default(1200),
  systemPrompt: text("system_prompt"),
  autonomyMode: text("autonomy_mode").notNull().default("assisted"),
  canAutoReply: boolean("can_auto_reply").notNull().default(false),
  canCreateRegistration: boolean("can_create_registration").notNull().default(false),
  canCreatePreOrder: boolean("can_create_pre_order").notNull().default(false),
  canHandoff: boolean("can_handoff").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_agent_configs_client_idx").on(table.clientId),
  operationIdx: index("ai_agent_configs_operation_idx").on(table.operationId),
  typeIdx: index("ai_agent_configs_type_idx").on(table.clientId, table.agentType),
}));

export const aiPricingConfigsTable = pgTable("ai_pricing_configs", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  operationId: text("operation_id").references(() => aiCommercialOperationsTable.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(),
  modelOrCategory: text("model_or_category").notNull(),
  market: text("market"),
  currency: text("currency").notNull().default("USD"),
  inputPricePerMillionTokens: doublePrecision("input_price_per_million_tokens").notNull().default(0),
  cachedInputPricePerMillionTokens: doublePrecision("cached_input_price_per_million_tokens").notNull().default(0),
  outputPricePerMillionTokens: doublePrecision("output_price_per_million_tokens").notNull().default(0),
  transcriptionPricePerMinute: doublePrecision("transcription_price_per_minute").notNull().default(0),
  imagePricePerMillionTokens: doublePrecision("image_price_per_million_tokens").notNull().default(0),
  whatsappDeliveredMessagePrice: doublePrecision("whatsapp_delivered_message_price").notNull().default(0),
  whatsappCategory: text("whatsapp_category"),
  freeServiceWindowEnabled: boolean("free_service_window_enabled").notNull().default(true),
  freeEntryPointWindowEnabled: boolean("free_entry_point_window_enabled").notNull().default(false),
  agencyMarkupPercent: doublePrecision("agency_markup_percent").notNull().default(0),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_pricing_configs_client_idx").on(table.clientId),
  activeIdx: index("ai_pricing_configs_active_idx").on(table.clientId, table.isActive),
}));

export const aiLeadProfilesTable = pgTable("ai_lead_profiles", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  whatsappContactId: text("whatsapp_contact_id").references(() => whatsappContactsTable.id, { onDelete: "set null" }),
  whatsappConversationId: text("whatsapp_conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "set null" }),
  customerId: text("customer_id").references(() => customersTable.id, { onDelete: "set null" }),
  upzeroCustomerId: text("upzero_customer_id"),
  name: text("name"),
  email: text("email"),
  phone: text("phone"),
  documentType: text("document_type"),
  documentHash: text("document_hash"),
  documentLast4: text("document_last4"),
  businessType: text("business_type"),
  city: text("city"),
  state: text("state"),
  qualificationStatus: text("qualification_status").notNull().default("unknown"),
  qualificationScore: integer("qualification_score").notNull().default(0),
  registrationStatus: text("registration_status").notNull().default("UNKNOWN"),
  createdByAgent: boolean("created_by_agent").notNull().default(false),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_lead_profiles_client_idx").on(table.clientId),
  conversationIdx: index("ai_lead_profiles_conversation_idx").on(table.whatsappConversationId),
  customerIdx: index("ai_lead_profiles_customer_idx").on(table.customerId),
  statusIdx: index("ai_lead_profiles_status_idx").on(table.clientId, table.registrationStatus),
}));

export const aiRegistrationAttemptsTable = pgTable("ai_registration_attempts", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  conversationId: text("conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "set null" }),
  whatsappContactId: text("whatsapp_contact_id").references(() => whatsappContactsTable.id, { onDelete: "set null" }),
  leadProfileId: text("lead_profile_id").references(() => aiLeadProfilesTable.id, { onDelete: "set null" }),
  customerId: text("customer_id").references(() => customersTable.id, { onDelete: "set null" }),
  upzeroCustomerId: text("upzero_customer_id"),
  status: text("status").notNull().default("draft"),
  payload: jsonb("payload"),
  apiResponse: jsonb("api_response"),
  errorMessage: text("error_message"),
  createdByAgentConfigId: text("created_by_agent_config_id").references(() => aiAgentConfigsTable.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_registration_attempts_client_idx").on(table.clientId),
  statusIdx: index("ai_registration_attempts_status_idx").on(table.clientId, table.status),
}));

export const aiCrmCardsTable = pgTable("ai_crm_cards", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  conversationId: text("conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "set null" }),
  customerId: text("customer_id").references(() => customersTable.id, { onDelete: "set null" }),
  whatsappContactId: text("whatsapp_contact_id").references(() => whatsappContactsTable.id, { onDelete: "set null" }),
  leadProfileId: text("lead_profile_id").references(() => aiLeadProfilesTable.id, { onDelete: "set null" }),
  stage: text("stage").notNull().default("new_contact"),
  previousStage: text("previous_stage"),
  intent: text("intent"),
  priority: text("priority").notNull().default("medium"),
  estimatedValue: doublePrecision("estimated_value").notNull().default(0),
  assignedToType: text("assigned_to_type").notNull().default("ai"),
  assignedToUserId: text("assigned_to_user_id"),
  handoffRequired: boolean("handoff_required").notNull().default(false),
  handoffReason: text("handoff_reason"),
  lastInteractionAt: timestamp("last_interaction_at", { withTimezone: true }),
  nextActionAt: timestamp("next_action_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_crm_cards_client_idx").on(table.clientId),
  conversationIdx: index("ai_crm_cards_conversation_idx").on(table.conversationId),
  customerIdx: index("ai_crm_cards_customer_idx").on(table.customerId),
  stageIdx: index("ai_crm_cards_stage_idx").on(table.clientId, table.stage),
  handoffIdx: index("ai_crm_cards_handoff_idx").on(table.clientId, table.handoffRequired),
}));

export const aiConversationInsightsTable = pgTable("ai_conversation_insights", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  conversationId: text("conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "cascade" }),
  insightType: text("insight_type").notNull(),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  evidence: jsonb("evidence"),
  recommendedAction: text("recommended_action"),
  impact: text("impact"),
  status: text("status").notNull().default("open"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_conversation_insights_client_idx").on(table.clientId),
  conversationIdx: index("ai_conversation_insights_conversation_idx").on(table.conversationId),
  statusIdx: index("ai_conversation_insights_status_idx").on(table.clientId, table.status),
}));

export const aiAgentRunsTable = pgTable("ai_agent_runs", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  conversationId: text("conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "set null" }),
  messageId: text("message_id").references(() => whatsappMessagesTable.id, { onDelete: "set null" }),
  agentConfigId: text("agent_config_id").references(() => aiAgentConfigsTable.id, { onDelete: "set null" }),
  agentType: text("agent_type").notNull(),
  model: text("model").notNull(),
  input: jsonb("input"),
  contextUsed: jsonb("context_used"),
  toolCalls: jsonb("tool_calls"),
  decision: text("decision"),
  draftResponse: text("draft_response"),
  finalResponse: text("final_response"),
  riskScore: doublePrecision("risk_score").notNull().default(0),
  blockedReason: text("blocked_reason"),
  inputTokens: integer("input_tokens").notNull().default(0),
  cachedInputTokens: integer("cached_input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  audioMinutes: doublePrecision("audio_minutes").notNull().default(0),
  imageTokens: integer("image_tokens").notNull().default(0),
  openaiCost: doublePrecision("openai_cost").notNull().default(0),
  whatsappCost: doublePrecision("whatsapp_cost").notNull().default(0),
  totalCost: doublePrecision("total_cost").notNull().default(0),
  latencyMs: integer("latency_ms").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  clientIdx: index("ai_agent_runs_client_idx").on(table.clientId),
  conversationIdx: index("ai_agent_runs_conversation_idx").on(table.conversationId),
  agentIdx: index("ai_agent_runs_agent_idx").on(table.agentConfigId),
  createdIdx: index("ai_agent_runs_created_idx").on(table.clientId, table.createdAt),
}));

export const aiMediaEventsTable = pgTable("ai_media_events", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  conversationId: text("conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "set null" }),
  messageId: text("message_id").references(() => whatsappMessagesTable.id, { onDelete: "set null" }),
  mediaType: text("media_type").notNull(),
  mimeType: text("mime_type"),
  filename: text("filename"),
  caption: text("caption"),
  metaMediaId: text("meta_media_id"),
  transcription: text("transcription"),
  visionSummary: text("vision_summary"),
  extractedText: text("extracted_text"),
  analysisStatus: text("analysis_status").notNull().default("pending"),
  errorMessage: text("error_message"),
  openaiCost: doublePrecision("openai_cost").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ai_media_events_client_idx").on(table.clientId),
  conversationIdx: index("ai_media_events_conversation_idx").on(table.conversationId),
  statusIdx: index("ai_media_events_status_idx").on(table.clientId, table.analysisStatus),
}));

export const ecommerceWebhookConfigsTable = pgTable("ecommerce_webhook_configs", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  isEnabled: boolean("is_enabled").notNull().default(false),
  secretHash: text("secret_hash"),
  sourceName: text("source_name").notNull().default("upzero"),
  allowedEventTypes: jsonb("allowed_event_types"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ecommerce_webhook_configs_client_idx").on(table.clientId),
  clientUnique: uniqueIndex("ecommerce_webhook_configs_client_unique").on(table.clientId),
}));

export const ecommerceWebhookEventsTable = pgTable("ecommerce_webhook_events", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  eventId: text("event_id"),
  eventType: text("event_type").notNull(),
  externalCustomerId: text("external_customer_id"),
  externalOrderId: text("external_order_id"),
  externalCartId: text("external_cart_id"),
  externalCheckoutId: text("external_checkout_id"),
  payload: jsonb("payload"),
  normalizedPayload: jsonb("normalized_payload"),
  status: text("status").notNull().default("received"),
  errorMessage: text("error_message"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("ecommerce_webhook_events_client_idx").on(table.clientId),
  eventTypeIdx: index("ecommerce_webhook_events_type_idx").on(table.clientId, table.eventType),
  statusIdx: index("ecommerce_webhook_events_status_idx").on(table.clientId, table.status),
  occurredIdx: index("ecommerce_webhook_events_occurred_idx").on(table.clientId, table.occurredAt),
  eventUnique: uniqueIndex("ecommerce_webhook_events_client_event_unique").on(table.clientId, table.eventId),
}));

export const commercialAutomationRulesTable = pgTable("commercial_automation_rules", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  operationId: text("operation_id").references(() => aiCommercialOperationsTable.id, { onDelete: "cascade" }),
  eventType: text("event_type").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  isEnabled: boolean("is_enabled").notNull().default(false),
  templateId: text("template_id"),
  templateName: text("template_name"),
  templateLanguage: text("template_language"),
  templateCategory: text("template_category"),
  delayMinutes: integer("delay_minutes").notNull().default(0),
  sendWindowStart: text("send_window_start"),
  sendWindowEnd: text("send_window_end"),
  cooldownHours: integer("cooldown_hours").notNull().default(24),
  maxSendsPerCustomerMonth: integer("max_sends_per_customer_month").notNull().default(4),
  conditions: jsonb("conditions"),
  variableMapping: jsonb("variable_mapping"),
  mediaSettings: jsonb("media_settings"),
  costSettings: jsonb("cost_settings"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("commercial_automation_rules_client_idx").on(table.clientId),
  eventTypeIdx: index("commercial_automation_rules_event_idx").on(table.clientId, table.eventType),
  enabledIdx: index("commercial_automation_rules_enabled_idx").on(table.clientId, table.isEnabled),
}));

export const commercialAutomationJobsTable = pgTable("commercial_automation_jobs", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  ruleId: text("rule_id").references(() => commercialAutomationRulesTable.id, { onDelete: "cascade" }),
  eventId: text("event_id").references(() => ecommerceWebhookEventsTable.id, { onDelete: "set null" }),
  conversationId: text("conversation_id").references(() => whatsappConversationsTable.id, { onDelete: "set null" }),
  customerId: text("customer_id").references(() => customersTable.id, { onDelete: "set null" }),
  whatsappContactId: text("whatsapp_contact_id").references(() => whatsappContactsTable.id, { onDelete: "set null" }),
  orderId: text("order_id"),
  status: text("status").notNull().default("scheduled"),
  scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(),
  processedAt: timestamp("processed_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  skipReason: text("skip_reason"),
  errorMessage: text("error_message"),
  renderedPayload: jsonb("rendered_payload"),
  whatsappMessageIds: jsonb("whatsapp_message_ids"),
  mediaSent: jsonb("media_sent"),
  openaiCost: doublePrecision("openai_cost").notNull().default(0),
  whatsappCost: doublePrecision("whatsapp_cost").notNull().default(0),
  totalCost: doublePrecision("total_cost").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => ({
  clientIdx: index("commercial_automation_jobs_client_idx").on(table.clientId),
  ruleIdx: index("commercial_automation_jobs_rule_idx").on(table.ruleId),
  statusIdx: index("commercial_automation_jobs_status_idx").on(table.clientId, table.status),
  scheduledIdx: index("commercial_automation_jobs_scheduled_idx").on(table.clientId, table.scheduledAt),
}));

export const commercialAutomationLogsTable = pgTable("commercial_automation_logs", {
  id: text("id").primaryKey().$defaultFn(() => nanoid()),
  clientId: text("client_id").notNull().references(() => clientsTable.id, { onDelete: "cascade" }),
  ruleId: text("rule_id").references(() => commercialAutomationRulesTable.id, { onDelete: "set null" }),
  jobId: text("job_id").references(() => commercialAutomationJobsTable.id, { onDelete: "set null" }),
  eventType: text("event_type").notNull(),
  action: text("action").notNull(),
  status: text("status").notNull(),
  message: text("message"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  clientIdx: index("commercial_automation_logs_client_idx").on(table.clientId),
  statusIdx: index("commercial_automation_logs_status_idx").on(table.clientId, table.status),
  eventTypeIdx: index("commercial_automation_logs_event_idx").on(table.clientId, table.eventType),
}));
